name: HTML validation
on:
  push:
    branches:
    - !main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@v7.1.1
        with:
          root: /
